[project]
name = "todo-python"
version = "0.1.0"
description = "Basic Todo app written in Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.14",
    "requests>=2.32.4",
    "uvicorn>=0.35.0",
]
