apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-python
  name: todo-python
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-python
  template:
    metadata:
      labels:
        app: todo-python
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: 'quay.io/jkeam/todo-python@sha256:82044e3f83364c1e61bfc81a03929511387e2d5101f9fb233045184668ea691b'
        name: todo-python
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "3000m"
        ports:
        - name: the-port
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: the-port
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: the-port
          initialDelaySeconds: 5
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /health
            port: the-port
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
