apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todo

images:
- name: IMAGE
  newName: quay.io/jkeam/todo-python
  digest: sha256:acea9f04bc7599206248b4c5cbb9e684fc5c05cfcf77bcca668e489b10df647f

resources:
- deployment.yaml
- service.yaml
- route.yaml
