apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-python
  name: todo-python
  namespace: todo
spec:
  ports:
  - name: service-port
    port: 8080
    protocol: TCP
    targetPort: the-port
  selector:
    app: todo-python
  type: ClusterIP
